#!/bin/sh
set -e

CONF=/etc/ldapscripts/ldapscripts.conf

if [ "$1" = "configure" ]; then
    zcat /usr/share/doc/ldapscripts/examples/ldapscripts.conf.gz \
	 >$CONF.example
    ucf --three-way $CONF.example $CONF
    ucfr ldapscripts $CONF
    rm -f $CONF.example
fi

#DEBHELPER#
